### ISSUE TITLE
GPL inclusion

### ISSUE THREAD

**Issue by paleajed** [bacondither/Adaptive-sharpen#1]
Hello,

I would like to include the adaptive sharpen code in my GPL v3 video mixer project EWOCvj2 (also on Github).  I can, of course, include your license block in the code, if so you wish...  The guys at libretro already were supposing it would be no problem, but I thought I'd ask straight at the source (:D)

Great code!

Gert De Roost.

**Comment by bacondither** [comment]
Thanks!

I have no problem with you including it in your project, but please keep the 2-clause BSD license block.

Have fun!
